browser = chrome
#url = https://www.saucedemo.com
url = https://ability-dream-6004.my.salesforce.com
team = baps
featureFilePath = src/test/java/org/qa/automation/features


morongwa.database.url =
morongwa.database.username = 
morongwa.database.password =